[build]
  base = "client"
  command = "npm run build"
  publish = "client/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_API_URL = "YOUR_BACKEND_URL"
  REACT_APP_SOCKET_URL = "YOUR_BACKEND_URL"
